### ISSUE TITLE
deriving via Last

### ISSUE THREAD

**Issue by georgefst** [reanimate/reanimate-svg#26]
The persistent use of `Last` adds a fair bit of noise to using this library, both when transforming attributes, and when looking at document ASTs (which are otherwise very readable with `pretty-simple`).

In recent GHC versions, we could get the same behaviour by using `DerivingVia` for the `Monoid` instances, without needing to wrap everything.

This would of course be a breaking change, and I'd understand if you don't think it's worth it.

**Comment by Lemmih** [comment]
I think it would be worth it.

**Comment by georgefst** [comment]
Great. I'll get to work.
