### ISSUE TITLE
Some typos in document

### ISSUE THREAD

**Issue by Cj-bc** [reanimate/reanimate-svg#29]
I think I found some typos in haddock. Can I make PR to fix this?
As I'm not English native nor good at this area, I want to check whether my thought is correct.

I think those are typo and correct word:

(`poitn` -> `point`?)
https://github.com/reanimate/reanimate-svg/blob/37972068f13551280e5712aa4c1b7f9bc5343e8a/src/Graphics/SvgTree/Types/Basic.hs#L24

(`possile` -> `possible`?)
https://github.com/reanimate/reanimate-svg/blob/37972068f13551280e5712aa4c1b7f9bc5343e8a/src/Graphics/SvgTree/Types/Basic.hs#L90

**Comment by Lemmih** [comment]
Nicely spotted. Those are indeed typos. I look forward to your PR.

**Comment by Cj-bc** [comment]
Ok, thank you! I created PR!

**Comment by Lemmih** [comment]
Merged.
